package frc.robot.subsystems;

import edu.wpi.first.networktables.GenericEntry;
import edu.wpi.first.wpilibj.shuffleboard.Shuffleboard;
import edu.wpi.first.wpilibj.shuffleboard.ShuffleboardTab;
import edu.wpi.first.wpilibj2.command.Command;

import java.util.function.Supplier;

import com.ctre.phoenix.ErrorCode;
import com.ctre.phoenix.led.CANdle.LEDStripType;
import com.ctre.phoenix.led.CANdle;
import com.ctre.phoenix.led.CANdleConfiguration;
import com.ctre.phoenix.led.CANdleFaults;
import com.ctre.phoenix.led.RainbowAnimation;

import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import frc.robot.Constants;

public class CanDle extends SubsystemBase{
    CANdle candle = new CANdle(0); // creates a new CANdle with ID 0
    // TalonFXConfiguration pidconfig = new TalonFXConfiguration().withSlot0(new Slot0Configs().withKP(1).withKI(0).withKD(0));
    public CanDle() {
        // Example usage of a CANdle


 CANdleConfiguration config = new CANdleConfiguration();
 config.stripType = LEDStripType.RGB; // set the strip type to RGB
 config.brightnessScalar = 0.5; // dim the LEDs to half brightness
 candle.configAllSettings(config);

    candle.setLEDs(255,0,255);
 

 // create a rainbow animation:
 // - max brightness
 // - half speed
 // - 64 LEDs
 RainbowAnimation rainbowAnim = new RainbowAnimation(1, 0.5, 7);


 ErrorCode error = candle.getLastError(); // gets the last error generated by the CANdle
 CANdleFaults faults = new CANdleFaults();
 ErrorCode faultsError = candle.getFaults(faults); // fills faults with the current CANdle faults; returns the last error generated
    

}
public void setLed() {
    candle.setLEDs(255,0,255);
  }
}